userguide/_static/themes/trueos_style/static/css/trueos_style.css
- Altered themeing of :guilabel: directives to avoid all caps.
=> Small change to :guilabel: directive:

userguide/_static/themes/trueos_style/static/css/trueos_style.css, userguide/conf.py
- Adding in all the reworked style elements to roles and directives.
- Also applied the menuselection arrow patch to the conf.py file, with comments.
=> Apply updated trueos_style, apply menuselection arrow patch.

userguide/_static/themes/trueos_style/static/css/trueos_style.css
- Changed font sizes for lvl 1-5 section headers.
- Commented out TrueOS logo use in TOC.
=> trueos_style.css changes:

userguide/_static/themes/trueos_style/layout.html, userguide/_static/themes/trueos_style/searchbox.html, userguide/_static/themes/trueos_style/searchresults.html, userguide/_static/themes/trueos_style/static/css/trueos_style.css, userguide/conf.py
Here's Google Search functionality for the FreeNAS Docs.  Please let me know if you have any questions!
=> Here's Google Search functionality for the FreeNAS Docs.

userguide/intro.rst, userguide/vms.rst
https://github.com/freenas/freenas-docs/issues/18
https://bugs.freenas.org/issues/23977
=> Fixes GiHub Issue #18 and adds information regarding FreeNAS Bug #23977

userguide/tn_cinder.rst
See commit messages for detailed notes about changes.
Build test with both commits: no errors or warnings.
=> Further edits to Cinder documentation:

userguide/jails.rst
See commit messages for details.
Resolves bug #26343 : https://bugs.freenas.org/issues/26343
=> Update Jails/iocage handbook sections

userguide/snippets/es60.rst
Rework a number of sentences for flow and minor errors.
Rework/remove a few sentences for the use of "you".
Fix a few syntax errors with admonition boxes.
Add comments for image placement.
=> Early text reworks: ES60

userguide/snippets/es60.rst
Using the es24 bsg as a template of sorts, work on the structure and syntax of the es60 bsg.
=> Continuing minor improvements to es60 bsg:

userguide/snippets/es60.rst
- Continue to update the structure of the ES60 BSGs to match the ES12/ES24 BSGs.
- Integrate text from Sam's ES60 photo list doc into the file.
- Save original text as comments in case it is needed.
- Add more commented notes for continuing work.
- Add specific names of images that still need to be integrated into the repo and .rst file.
=> Continuing structural and text updates to es60 BSG

userguide/services.rst, userguide/tasks.rst
Reverts freenas/freenas-docs#46
This requires a bit more editing before merge.
=> Revert "Rsync service + tasks"

userguide/services.rst
- This includes text cleanup, table reworks, and html link fixes.
- HTML Build testing: no issues.
=> Port angulargui text revisions to master branch for services.rst:

userguide/reporting.rst
Messed up in first draft and incorrectly explained the checkbox. Corrected it here.
=> Fixed mistake in explanation of Reporting database checkbox.

userguide/logout.rst
- Remove line about logging back in to the ui.
=> Port text rework from angulargui to master branch:

userguide/processes.rst
- Removed unnecessary text about the system processes window.
=> Port angulargui text improvements to master branch:

userguide/network.rst
- Review the angulargui version of network.rst and port any text improvements
separate from new UI specific elements.
=> Port text improvements to network.rst from the angulargui branch.

userguide/sharing.rst
-Reformatted the tables to reflect our new style which does not include semicolons. 
-Removed you and your references. 
-Note: I found new text issues that will need to port them back to
angular.  
-Reworked sentences starting with "it is recommended". 
-Tested with no build errors.
=> Port text improvements from angular to master and add new improvements.

userguide/account.rst
- This includes table syntax improvements and any text reworks separate from new ui documentation.
=> Port text improvements from angulargui branch to master for account.rst:

userguide/account.rst
- Review "Groups" and "Users" sections to update text after tickets 30885, 30888, 30891, 30894, and 30897 are resolved.
- HTML build testing: no issues
=> Update account.rst after related tickets were resolved:

userguide/install.rst
Also added a few additional changes that will need to be added to the angular gui docs. Changes included removing you and your references. Changing passive sentences to active. Removing possessives.
=> Ported over text improvements from the angular gui docs. 

userguide/cli.rst
-capitalize Iperf consistently throughout.
-test the build.
-remove "the following" references because Warren doesn't like those.
=> Port text improvements from angular and make a few more along the way.

userguide/storage.rst
Clarify 88 ascii character limit
=> Fix wrapping issues

userguide/snippets/pathlengths.rst
Added proper warning and notes. Rework the text a bit for clarity.
=> Fix wrapping issues and rework text

userguide/storage.rst
Renamed disks: to disks
added an Index:: Disks entry
=> Fix undefined label: disks error

userguide/account.rst
-passed build test with no errors.
=> Port text improvements from angulargui.

userguide/conf.py
=> Attempt to make the UI icons stand out better by bolding the symbols:

userguide/conf.py
=> Update utf-8 character for the |ui-options| role.

userguide/quick.rst
- Review the text and make a few alterations to reflect the angular ui.
- Leave a comment about updating an IP address example when the relevant image is updated.
=> Review quick.rst to reflect the angular ui:

userguide/snippets/console_menu.rst
Update syntax slightly to make better use of Sphinx directives.
Changes will be ported to master branch
=> Review snippets/console_menu.rst and make a few change:

userguide/snippets/console_menu.rst
HTML Build testing: no issues.
=> Slight syntax revisions to console_menu.rst:

userguide/network.rst
- Added our new UI symbols, where applicable. 
- Replaced "checked" with "set".
- Changed sentences from passive to active.
=> Reviewed the network.rst to ensure it matches the new UI.

userguide/system.rst
=> Review and update system.rst to reflect the new UI:

userguide/shutdown.rst
=> Review and update shutdown.rst to reflect the new UI.

userguide/directoryservice.rst
Review of directoryservices.rst
=> Directoryservice review

userguide/plugins.rst
- Review the text and rewrite to match the flow of the new ui.
- Update plugin creation/submission section to explain the flow a little more.
- Update available plugin list to list official plugins that are currently present in the FreeNAS UI.
=> Review and rewrite plugins.rst:

userguide/contribute.rst
- Small changes to clarify workflow and where buttons are located.
- This is a complete rewrite based on the new translation system used by the new Angular UI.
This file should not be backported to the master branch of freenas-docs, at least until the old UI translation system is retired in favor of this new method.
=> Review contribute.rst:

userguide/plugins.rst, userguide/quick.rst, userguide/shutdown.rst, userguide/system.rst, userguide/tasks.rst, userguide/vms.rst
vms, tasks, system, shutdown, quick, and plugins.
=> Port angulargui text improvements to master for a few files:

userguide/services.rst
Finally finished reviewing this massive section! 
-Reviewed the text to make sure it matched the new UI.
-Moved over tooltip text improvements to the table text.
-Added our new icon conventions
-Incorporate our new writing style conventions to improve flow. Example: replace "log on" with "log in", remove "you" and "your" references, replace "check" with "set", etc.
-Change sentences from active to passive by replacing to be with is, for example.
-No errors when I tested the build.
=> Review services.rst:

userguide/services.rst
This took way longer than expected as I ran into an "unexpected indentation" error that really put a dent in my brain. After much pain and loss of sanity, it now builds with no errors. While porting the improvements I noticed quite a few errors in Angular that I missed that I'll have to go back and fix.
=> Ported services.rst text improvements from Angular to Master.

userguide/snippets/alertevents.rst
=> Ported alertevents.rst improvements to master.

userguide/support.rst
Minor clean up of text. 
Removed you and your references.
Passed built test with no errors.
=> Made minor adjustments to support.rst.

userguide/support.rst
=> Ported support.rst text improvements to master.

userguide/account.rst, userguide/cli.rst, userguide/install.rst, userguide/intro.rst, userguide/network.rst, userguide/processes.rst, userguide/reporting.rst, userguide/services.rst, userguide/sharing.rst, userguide/snippets/alertevents.rst, userguide/storage.rst, userguide/support.rst, userguide/system.rst, userguide/tasks.rst, userguide/vaai.rst, userguide/vms.rst, userguide/zfsprimer.rst
External link check and link syntax update:
- Run make linkcheck and fix all errors or warnings with links.
- Update link syntax from `_ -> `__
- Fix some whitespace and line length issues in the .rst files.
- HTML build testing: no issues
=> Angulargui link review

userguide/vms.rst
-Review text to verify it matches up with new UI and made adjustments where necessary. 
-Updated text in tables to match our current style.
-Added our new UI elements as needed.
-Changed sentences from passive to active.
-Passed build test with no errors.
=> Reviewed VMs.rst:

userguide/vms.rst
-Passed the build test with no errors.
=> Ported vms.rst text improvements to master.

userguide/jails.rst
This commit is not fully ready. Need to speak to Warren about a couple of screenshot changes namely screenshots changing names or the name for an additional screenshot.
=> Jails review

userguide/sharing.rst
-Finally finished this massive review. 
-Went through each section to ensure it matched up with the UI. Found a lot of sections that needed to be updated based on UI changes. 
-Added way too many |ui-add| and |ui-option| icons. 
-Solved numerous build errors.
-Reviewed the changes in a browser, and caught a bunch of errors that didn't show up as sphinx errors, like forgetting the `  in a :menuselection: or a Figure. 
-Updated all the tables to conform to our style.
-Removed you and your references.
=> Reviewed sharing.rst:

userguide/services.rst
Fix instances where :guilabel: was used incorrectly.
=> Fix some formatting errors I missed in services.rst.

userguide/plugins.rst
Plugins added:
Bacula
irssi
qbittorrent
weechat
XMRig
Linked to the project homepage and used the brief description there.
Removed you/your use
=> Add the new plugins available to the angular docs

userguide/system.rst
Certificate Identifiers are the only fields that are editable
Certificate and Private Key fields are read only
=> Update Edit to reflect updated certificate fields

userguide/system.rst
Only the Identifier field is editable for a Certificate
=> Update system with current editable field

userguide/storage.rst
Passed build test with no errors.
Removed you and your references.
Removed incorrect usage of possessives (dataset's, volume's, etc.)
Adjusted tables to fit our new format.
=> Ported general text improvements to master.

userguide/snippets/upgradingazfspool.rst
Added our new UI symbol where applicable. 
Passed build test with no errors.
=> Reviewed upgradingazfspool.rst:

userguide/install.rst
=> (#37228) Update FreeNAS .iso name in the dd example:

userguide/install.rst
=> Update dd examples with BETA1 iso name.

userguide/system.rst
Reviewed instructions for accuracy with current UI.
Reformatted tables based on Tim's guidelines, which were: remove semicolons, capitalize sentences, add period to end of sentence, add an empty line to table rows, and two empty lines after the table is finished. 
Removed you and your references.
Changed checkboxes to options.
Changed passive sentences to active. 
Reworked sentences with improper use of possessives.
=> Reviewed the system.rst:

userguide/install.rst
=> Update install.rst to be version agnostic in the "dd" examples:

userguide/install.rst
=> Update dd command examples to be FreeNAS version agnostic:

userguide/system.rst
- Also fix broken internal reference link.
- Rework the configuration file download instruction to reflect the legacy ui flow.
=> Synchronize text improvements from angulargui branch into master:

userguide/api.rst
-Reviewed text to ensure it was in sync with the new UI.
-Updated the table to reflect our current style.
-Removed incorrect use of possessives. 
-Fixed incorrectly formatted links. 
-Passed build test with no errors.
=> Added changes by Waqar and did a full review on the entire document.

userguide/api.rst
=> Note for API v2 added

userguide/intro.rst
Added note about zooming in firefox.
=> Updated docs with regard to ticket #34768.

userguide/tasks.rst
=> Fixed the description of Validate Remote Path checkbox.

userguide/vms.rst
The screenshot also needs to be updated since last review, but will wait for the automated screenshot tool to retake all of them.
=> In review of ticket #35293 I found that I needed to edit some text

userguide/sharing.rst
- Removed warning that vfs_full_audit may cause transfer problems with the Windows 10. 
- Passed build test with no errors.
=> Updated docs in response to ticket 32055. Will update master next.

userguide/sharing.rst
-Passed build test with no errors.
=> Ported changes from angular based on review of ticket 32055.

userguide/system.rst
- HTML build test: two issues reported with api.rst, nothing related to this work.
=> Sync "Show Text Console without Password Prompt" description.

userguide/system.rst
This reflects the new field name in the new UI. The updated description can be ported
back to the master branch.
Notes:
- The screenshot needs to be updated so the new field name is visible.
- It might be useful to port the updated description into the tooltip.
=> Update System/Advanced table field name and description.

userguide/vms.rst
=> Rework resource link to only include it in the VM Wizard Options table.

userguide/vms.rst
- Used an admonition box for master as the legacy UI doesn't have
an entry for a "Guest OS".
=> Add "launch different Guest OS" resource to VMs chapter:

userguide/install.rst
- Clarify one explanation about the boot timer in line 410 area.
=> Port one minor change from angulargui PR:

userguide/sharing.rst
- Synchronize change from PR 234.
=> Fix 34384 [master branch]:

userguide/directoryservice.rst
=> Port kerberos keytab text reworks from PR 238

userguide/services.rst
=> Port text change from PR 240:

userguide/services.rst
=> Update Access Key and Secret Key descriptions: Port changes from PR 243.

userguide/snippets/alertevents.rst
- Add entry for NTP server error to alertevents.rst
=> Port change from PR 245 to master branch:

userguide/storage.rst
- Update the text in Storage/Managing Encrypted Pools to reflect the new UI.
- This is UI specific with nothing to port to master branch.
- Comment out text related to Redmine issue 39852.
=> Update text concerning options for a locked pool:

userguide/intro.rst
=> Port changes from PR 249 into angulargui branch:

userguide/tasks.rst
=> Port relevant changes from PR 253:

userguide/tasks.rst
- Added to Cloud Sync Options table.
- Will investigate and port to master branch if necessary.
=> Add text explaining the credential validation for Cloud Sync tasks:

userguide/intro.rst, userguide/system.rst
Add entry in intro.rst
Remove entry in system.rst
=> Document removal of console screen saver option:

userguide/system.rst
to reflect that. Also did some research about a few of the cloud credentials and added some instructions on how to get the access tokens for Google Cloud Storage and Dropbox. Also cleaned up a typo I noticed in another section. Need to port this to master next. Passed build test with no errors.
=> Support for 13 new cloud credentials was added so updated system.rst 

userguide/storage.rst
- Also fix incorrect button label.
=> Expand the instructions on decrypting/importing a pool a bit.

userguide/system.rst
Passed build test with no issues.
=> Fixed a few minor text issues I noticed in system.rst.

userguide/conf.py
=> Port PDF font fix from PR 269:

userguide/tasks.rst
Added a link as mentioned in [forum post](https://forums.freenas.org/index.php?threads/public-private-ssh-key-for-freenas-user.62390/#post-445165).
=> Add link that further explains ssh-keygen

userguide/tasks.rst
Added a note about scrubbing pools with regards to this [forum post](https://forums.freenas.org/index.php?threads/scheduled-scrub-didnt-happen.52219/#post-371921).
EDIT: If this change is approved, I'll port to master.
=> Added note about scrubbing pools.

userguide/tasks.rst
This note was added to angulargui branch in this [PR](https://github.com/freenas/freenas-docs/pull/272).
It needed a master change as well. 
This is the master change.
=> Added note about scrub task (master branch).

userguide/plugins.rst
Doc update for [ticket 39707](https://redmine.ixsystems.com/issues/39707)
=> Added sentence about confirmation msg for installing plugins.

userguide/system.rst
Fix for [ticket 39493](https://redmine.ixsystems.com/issues/39493).
=> Added text to reflect setting swap size 0 is bad.

userguide/intro.rst
=> Port change from PR 291 to master branch:

userguide/install.rst, userguide/intro.rst, userguide/sharing.rst, userguide/storage.rst, userguide/system.rst, userguide/zfsprimer.rst
=> Port necessary changes from PR 305:

userguide/install.rst, userguide/intro.rst, userguide/jails.rst, userguide/services.rst, userguide/sharing.rst, userguide/storage.rst, userguide/system.rst, userguide/wizard.rst, userguide/zfsprimer.rst
Search through the handbook and update terminology to match the industry standards and the FreeNAS UI.
Did not update representative code-blocks.
=> Update KiB, MiB, GiB, and TiB usage in handbook:

userguide/account.rst, userguide/conf.py
account.rst. 
Passed build test with no errors.
=>  Added a text replacement for webui to the conf file and tested it in 

userguide/account.rst, userguide/conf.py
=> Ported over the web ui text replacement role.

userguide/shell.rst
This is the master branch commit for #290
=> Updated master branch for shell.rst.

userguide/sharing.rst
=> Port changes in PR 321 to master branch:

userguide/plugins.rst
- Also adjust a few elements to use :literal: roles.
- Add warning that this procedure is to be used for testing only.
- Add examples
=> Add plugin branch download instructions to plugins.rst.

userguide/cli.rst, userguide/intro.rst
=> Add entries for new freenas-debug -J flag to intro.rst and cli.rst.

userguide/api.rst, userguide/booting.rst, userguide/cli.rst, userguide/directoryservice.rst, userguide/install.rst, userguide/network.rst, userguide/plugins.rst, userguide/power.rst, userguide/preferences.rst, userguide/services.rst, userguide/sharing.rst, userguide/shell.rst, userguide/storage.rst, userguide/system.rst, userguide/tasks.rst, userguide/vms.rst, userguide/zfsprimer.rst
Also fixed a few minor errors that were obvious like incorrect use of possessives, use of you, incorrect capitalization of iperf, and so on.
=> Replaced every UI, GUI, and graphical interface to use a sphinx role.

userguide/account.rst, userguide/directoryservice.rst, userguide/install.rst, userguide/intro.rst, userguide/jails.rst, userguide/network.rst, userguide/plugins.rst, userguide/power.rst, userguide/preferences.rst, userguide/services.rst, userguide/sharing.rst, userguide/shell.rst, userguide/snippets/alertevents.rst, userguide/snippets/pathlengths.rst, userguide/storage.rst, userguide/system.rst, userguide/tasks.rst, userguide/vms.rst
Redmine issue 37258 https://redmine.ixsystems.com/issues/37258#change-275357
Other elements addressed in these commits:
- Line spacing and empty lines.
- Field names.
- Table adjustments related to field names.
- Small text adjustments.
- Remove obsolete comments.
=> Review FreeNAS Guide and update button labels to new standards

userguide/storage.rst
This was going to be an improvement for ticket 39842, but Tim covered it in his PR #318  before I got to it. So in my review of his merged work I found a couple of possessives that needed correcting.
=> Improved style--removed some possessives.

userguide/account.rst, userguide/intro.rst, userguide/jails.rst, userguide/network.rst, userguide/services.rst, userguide/sharing.rst, userguide/shell.rst, userguide/snippets/pathlengths.rst, userguide/system.rst, userguide/tasks.rst, userguide/vms.rst
=> Port small changes from 37258 angular fix to master branch.

userguide/vms.rst
=> Port changes from PR 335 to master branch.

userguide/sharing.rst
=> Update text about Sharing > NFS > Path field.

userguide/storage.rst
=> Port changes from PR 352 to master branch:

userguide/vms.rst
=> Update text about shutting down or stopping a vm.

userguide/network.rst
=> Port UI agnostic changes from PR 350 (Update lagg documentation).

userguide/jails.rst
=> Update BPF description to show it is unset by default.

userguide/install.rst, userguide/quick.rst
=> Port changes from PR 359 to master branch:

userguide/system.rst
=> Add text indicating Name field for new Cloud Credentials must be unique.

userguide/jails.rst, userguide/plugins.rst
=> Add notes about creating a pool for iocage to jails.rst and plugins.rst:

userguide/system.rst
=> Update entry for Backblaze B2 Cloud Credentials.

userguide/jails.rst, userguide/storage.rst
- Add internal reference point to the storage chapter.
- Verify upgrading a jail can be done through the UI.
=> (42857) Add text about updating or upgrading a jail:

userguide/sharing.rst
=> Add back in archived version of article from broken website:

userguide/sharing.rst, userguide/system.rst
Also present is a clean up of my local branch - no changes from this.
HTML testing: no issues.
=> Port changes from PR 367

userguide/jails.rst
Also clean up a few obsolete bits of text in the jail introduction.
=> Update jail documentation to reflect changing active iocage datasets:

userguide/snippets/pathlengths.rst
=> Port missing path lengths text from master branch to angulargui:

userguide/vms.rst
=> Add brief text about error messages when cloning a VM.

userguide/conf.py, userguide/vms.rst
Rework text to more closely match legacy ui flow where necessary.
=> Remove httpdomain extension and port changes from PR 389

userguide/vms.rst
=> Updated vms section, particular to ticket 40496.

userguide/reporting.rst
I didn't see any major changes. The screenshots were up to date and all the tabs were the same. The only thing I noticed was the magnifying glass and  >> << were added. They will have the same functionality as the old UI. I used the docs from the old guide since the functionality is the same. 
I also updated the part about hovering over the graph to zoom in on it. Before you could use the scroll wheel but I couldn't get that to work. The process works just fine by clicking and dragging. 
This is in response to this doc item - https://redmine.ixsystems.com/issues/41176
=> Update text to reflect the new UI.

userguide/directoryservice.rst
Add text about clearing LDAP users and groups to Directory Services chapter.
=> 43943 docs angular

userguide/directoryservice.rst
=> Port changes from PR 400 to master branch:

userguide/jails.rst
- New UI only, no master PR needed.
=> Add documentation for new vnet_default_interface field.

userguide/intro.rst, userguide/system.rst
- Add entry in intro.rst for the checkbox rename on System/Update.
- Update related text in system.rst
=> Update System/Update text:

userguide/jails.rst, userguide/plugins.rst
=> Add text about Restart option for Jails/Plugins.

userguide/jails.rst, userguide/plugins.rst
=> Add warnings about managing jails and plugins with the legacy UI.

userguide/sharing.rst
=> 50423: Add text about setting a LUN ID of 0 for an Associated Target.

userguide/system.rst
=> Update Backblaze B2 field descriptions.

userguide/intro.rst, userguide/vms.rst
- Update entry in intro.rst to mention this new option.
- Port text to vms.rst from the UI to explain the new field.
=> 48680: Document new "Overcommit Memory" option for VMs:

userguide/vms.rst
- Clean up some unnecessarily long links.
- Clean up some clunky text.
- Rework docs about different views for the VMs page to better reflect the current UI.
=> Update text about VM view options and other small changes:

userguide/vms.rst
=> Port necessary changes from PR 427 to master branch:

userguide/system.rst
- passed build test with no issues.
=> Ported changes over from angular.

userguide/storage.rst
- Copy over Disk Options table and readjust to reflect legacy UI.
- Port over Disk bulk edit instructions and adjust to reflect the legacy UI.
=> Port bulk edit instructions from PR 429 to master branch:

userguide/directoryservice.rst
=> Changed future tense title to present tense.

userguide/directoryservice.rst
master change from PR #433 
HTML build: no issues
=> Changed title from future tense to present (master change).

userguide/system.rst
Ported improvements to master from PR #422 .
=> Ported improvements to master from PR #422

userguide/account.rst
passed build test with no issues.
=> Ported tooltip changes over to docs from bug 52116.

userguide/account.rst
Passed build test with no issues.
Related to https://github.com/freenas/freenas-docs/pull/438.
=> Ported angular changes over to master.

userguide/sharing.rst
Cherry picked the commit from https://github.com/freenas/freenas-docs/pull/424/
Passed build test with no issues.
=> Ported changes over to master from angular. 

userguide/intro.rst, userguide/reporting.rst
- Add entries to intro.rst to reflect the changes to the Reporting page.
reporting.rst changes:
- Add instructions about generating reports on the Disk tab.
- Remove text about System Uptime graph.
- Update ZFS graph text.
=> Update Reporting text:

userguide/services.rst
Slight rework to match legacy UI.
=> Port changes from PR 435 to the master branch.

userguide/storage.rst
Passed build test.
Ported changes from https://github.com/freenas/freenas-docs/pull/444/commits/8edd1782a181be81757f5793901ed27526c59f97
=> Ported text changes over from angulargui.

userguide/intro.rst, userguide/settings.rst, userguide/system.rst
- Add entry in intro.rst.
- Add text to system.rst about the popup
- Add text to settings.rst about the popup.
=> 26198: Add text about new "Save Configuration" popup window

userguide/intro.rst, userguide/system.rst
Add entry to intro.rst to explain the change.
Add explanation to system.rst that only the possible update trains are shown in the UI.
=> Update docs to reflect the changes to update trains.

userguide/account.rst
moving up the last sentence. Ported these changes over from bug 52116.
Passed build test.
=> Clarified the docs by removing period after characters list and 

userguide/account.rst
Passed build test.
Changes are from https://github.com/freenas/freenas-docs/pull/455
=> Ported text improvements from angular.

userguide/storage.rst
Passed build test. 
Changes ported from https://github.com/freenas/freenas-docs/commit/2d61359c36e9692f16116db9b7029829108f9353
Ticket: #54261
=> Ported changes made by Warren as he requested.

userguide/help.rst, userguide/tn_options.rst
Passed build tests for both guides.
=> The UI guide now links to the online guide so I updated the TrueNAS and FreeNAS docs

userguide/booting.rst
=> Fix spelling error I found using grep.

userguide/plugins.rst
=> Update weechat.org link so it doesn't try to append on to the docs URL:

userguide/directoryservices.rst
=> Fix incorrect lables (angular fix).

userguide/tasks.rst
=> 54807: Update tasks.rst text about redirect standard output/error:

userguide/intro.rst
Reverts freenas/freenas-docs#487
=> Revert "Updated intro to include list of new providers for CC."

userguide/plugins.rst
Changes not applicable to master branch.
=> Add text to explain plugins cannot install more software.

userguide/intro.rst, userguide/settings.rst
- Update field name in settings.rst
- Review system.rst/update section to verify text matches ui behavior.
- Update field name in intro.rst and fix error with :menuselection: instance.
=> 54879: Update name of "Save Config" checkbox

userguide/network.rst
=> Port necessary changes from PR 500 to master branch:

userguide/services.rst
Also, slight text rework.
HTML build: no issues.
=> Clarified the Port field when selecting an snmp driver.

userguide/plugins.rst
Found no other instances that require updating.
=> 65220: Update quasselcore to plex in Plugins/Delete section:

userguide/snippets/contact.rst, userguide/snippets/es60.rst, userguide/snippets/userguide.rst
Update ES60 BSG:
Add note to beginning of document that ES60 replaced the E60 and add the EOL and EOS dates for the E60.
Reword paragraph about installing cage nuts to attempt to clarify. Investigation shows no photos available showing the specific process to install a cage nut.
Rework two included snippets to fix erroneously visible ..index:: entries and avoid automatic hyphenation.
=> Port PR 465 to master branch

userguide/sharing.rst
=> 60192: Update caution about used space of a pool with iSCSI to 80%:

userguide/sharing.rst
=> Update caution about used space of a pool with iSCSI to 80%:

userguide/tasks.rst
=> Clarified the cloud sync scheduling function.

userguide/storage.rst
Also provide a reference to the Self-Encrypting Drives section.
=> Update Storage/Managing Encrypted Pools to better explain ZFS "full disk" encryption.

userguide/sharing.rst
=> Add warning about allowed characters in target names

userguide/network.rst
=> Add max. character limit to IPMI password field

userguide/network.rst
=> Port PR 560 to freenas/11.1-stable branch:

userguide/system.rst
- Build testing: broken for TrueNAS guide in this branch.
=> Port PR 558 (note about GELI passphrase on login) to angulargui

userguide/sharing.rst
=> Port PR140 to angulargui branch:

userguide/system.rst
- Rework end of failover section into a list of general notes about HA and failover.
=> 31656: Add note about GELI passphrase requirement at UI login.

userguide/system.rst
=> Add text about character restrictions for SMTP passwords.

userguide/system.rst
=> Sync PR 574 (SMTP passwords) with master:

userguide/directoryservice.rst
=> Port PR 528 (tip about config AD with two FreeNAS systems) to master

userguide/vms.rst
=> Port PR 525 (nfs passthru section to vms.rst) to master branch:

userguide/storage.rst
- Add text for new "Date Created" column.
- Fix "Referenced" name.
- Check master branch: no ports of this PR are necessary.
- Check image storage-snapshots.png: this will be updated when the screenshot automation runs.
=> 65247: Update text describing columns in Storage/Snapshots:

userguide/intro.rst, userguide/vms.rst
=> 68473: Port PR600 to master branch:

userguide/directoryservice.rst
- Fix a couple errors in the table.
- Adjust spacing a bit for the Certificate entry.
- Will resync these changes to PR 596
=> 60792: Port PR 596 and a few incidental changes

userguide/directoryservice.rst
- Text applies to this version of the guide too.
=> 60792: Port PR596 to 11.1-stable

userguide/storage.rst
Add text about "promote dataset" button in the relevant location in storage.rst.
=> 61107: Port PR610 to master branch

userguide/storage.rst
Cherry pick 6776b5e [master] to 11.1 branch
=> 61107: Port PR610 to freenas/11.1 branch

userguide/services.rst
- Port previously accepted text from master branch to relevent section in services.rst.
- Verify an entry for this field is present in intro.rst.
- Related screenshot will be updated by automation.
=> 56013: Add "Enable SMB1 support" text to angulargui branch.

userguide/storage.rst
Relevant text needs to be ported to master and 11.1 branches.
=> 61107: Add text about promote dataset option to zvol configuration section

userguide/conf.py, userguide/intro.rst, userguide/snippets/copyright.rst, userguide/tn_intro.rst
=> Update copyright year.

userguide/intro.rst
No port to other branches is necessary.
=> 59397: Add entry to intro.rst about new column.

userguide/intro.rst, userguide/tasks.rst
- This is added to the Folder field.
- Related image will be updated as part of screenshot automation.
- This is angular UI only. No port to master.
=> 52607: Add text for new browse option in Tasks/Cloud Sync tasks/Add.

userguide/conf.py, userguide/intro.rst, userguide/snippets/copyright.rst, userguide/tn_intro.rst
=> Update copyright year

userguide/install.rst
=> Remove Microsoft Download Tool recommendation

userguide/system.rst
- Add text explaining submitting a ticket can take some time.
- Rework sentence explaining the URL popup.
- Need to port TrueNAS text improvements to the other branches
=> 53622: improve bug submission text

userguide/reporting.rst
=> 32793: Update reporting/ZFS section to reflect each graph.

userguide/reporting.rst
=> 32793: Retest and port PR637 (reporting.rst update) to angulargui.

userguide/system.rst
=> 67618: update SMTP password text

userguide/system.rst
=> 67618: port PR 640 (SMTP password text) to angulargui

userguide/system.rst
=> 53622: Port PR 623 (bug submit text) to master.

userguide/intro.rst
- Investigate the rest of the guide and did not find any other relevant text.
=> 33141: cherry pick PR647 (removed collectd IPMI plugin) to master.

userguide/system.rst
=> 66925: Port PR 649 (minimum CA/Cert key bit lengths) to master

userguide/storage.rst
- Rework description to reflect the root dataset space usage.
- Check related images dashboard.png, storage-pools.png, and storage-pools-actions-detach.png. All will be updated when screenshot automation is run.
=> 64728: Update pool available space description

userguide/intro.rst
Specific change to Angular GUI; no port to master branch needed.
=> 53638: Add entry to intro to note pool widgets in dashboard change colors

userguide/virtualmachines.rst
=> 62712: Update text and description for vm boot delay for vnc option

userguide/intro.rst, userguide/system.rst
- Add entries to Cloud Credential Options table in system.rst
- Add entry to intro.rst U2 section.
=> 63483: Document new S3 Credential checkboxes (master)

userguide/intro.rst, userguide/snippets/alertevents.rst
- Add entry in intro.rst for new alert.
- Add entry in alert list in snippets/alertevents.rst
=> 45398: Add syslog-ng alert

userguide/intro.rst
=> 30495: Add entry to intro about new ability to pin help text.

userguide/vms.rst
Port of PR671 to master branch.
=> Doc Queue Item 1: Add AHCI disk recommendation for VMs with a Windows OS

userguide/vms.rst
=> 67420: Port Docker VM text improvements to master

userguide/intro.rst, userguide/system.rst
Check PR 1834 in webui repo for any further changes that need to be made: https://github.com/freenas/webui/pull/1834
=> 63483: Document new Amazon S3 credential fields:

userguide/system.rst
=> 25705: Add text about downloading updates from a secure source

userguide/system.rst
=> 72459: Fix minor typo in system.rst/Cloud Credential Options table.

userguide/intro.rst
Field not present in legacy UI, no port to [master].
=> 59973: Add entry to intro.rst for new "Reboot After Update" field.

userguide/sharing.rst
Cherry-pick from PR681:https://github.com/freenas/freenas-docs/pull/681
=> Doc queue item 31: Add note about Windows disabling SMB2 guest access.

userguide/services.rst
=> 73191: services.rst: Add text about listing multiple domains for Dynamic DNS

userguide/services.rst
Cherry-pick from master branch PR. The table was identical apart from the the new proposed text, so I synced the table size between the two branches.
=> 73191: Add text about listing multiple domains for Dynamic DNS

userguide/tn_vcenter.rst
=> Rework vCenter doc to reflect the plugin WIP status.

userguide/intro.rst
Search through the guide for other re0 or realtek examples: no others found.
=> 70545 (11.2-U3): Replace re0 ifconfig example in intro.rst

userguide/directoryservices.rst, userguide/tasks.rst
Clean up a couple extra commits that crept into my branch.
=>  66430 (11.2-U3): Clarify replication process and interruptions.

userguide/storage.rst
Cherry-pick of PR 716 not possible as this text is in a different file for master branch.
=> 66430 (11.2-U3): Clarify replication process and interruptions.

userguide/system.rst
(cherry picked from commit 5ebbb19c74ee5b88fa105cfe6b7704dfffe429cc)
=> 75397: Update the list of default tunables and sysctl's.

userguide/virtualmachines.rst
As per [Warrens comment](https://github.com/freenas/freenas-docs/pull/616#pullrequestreview-195066552).
[Web UI change](https://github.com/freenas/webui/pull/1879)(master)
=> Match the labels the userguide for VM wizard options to labels in web UI

userguide/system.rst
(cherry picked from commit e814bba4eac16965c683dc4ed3aad4b2fdecf8c0)
=> remove 3 tunables from the truenas part.

userguide/sharing.rst
Synchronize text between legacy and new UIs.
=> 73650: Update "Access Based Share Enumeration" field description

userguide/_static/themes/trueos_style/static/css/trueos_style.css
=> Small typo in the font declaration

userguide/intro.rst, userguide/sharing.rst
Add entry to intro.rst for this object that replaced shadow_copy_test.
=> 75873: Document new shadow_copy_zfs VFS object.

userguide/sharing.rst
Ported angulargui change to legacy UI guide, as testing appears to show the same behavior in the legacy UI. I could use outside confirmation though.
=> 69186: Update LUN ID field description

userguide/intro.rst, userguide/virtualmachines.rst
=> 76701: Add Restart option to a Running VM.

userguide/intro.rst, userguide/reporting.rst
=> 65754: bits -> megabytes for graphs in Reporting > Network.

userguide/storage.rst
=> 70527: Port Multipath text improvements to master

userguide/intro.rst, userguide/storage.rst
Found similar reference to deleting a zvol farther in the master branch storage chapter - porting text improvement over.
=> 71619: Update zvol delete text to include snapshots.

userguide/intro.rst, userguide/reporting.rst
Also make small change in reporting to mention the new graphs.
=> 58437: Add entry for new CPU temperature graphs.

userguide/storage.rst
=> 71619: Update zvol delete description.

userguide/intro.rst, userguide/storage.rst
=> 71619: Remove zvol snapshot delete entry from intro.rst.

userguide/storage.rst
Begin with cherry-pick from #775 and will update when any further changes are made.
=> 76531: Sync with PR #775

userguide/sharing.rst
=> 69186: Expand LUN ID description

userguide/snippets/es60.rst
https://redmine.ixsystems.com/issues/78519
- Add sentence explaining the unit might need to be pulled slightly out of the rack to install the CMA bracket.
- PDF build test: no issues.
=> 78519: Update ES60 BSG CMA instructions

userguide/Makefile, userguide/conf.py
=> Cherry-pick menuselection arrow fix to master

userguide/Makefile, userguide/conf.py
(cherry picked from commit d7eca169760d0676f6cac1f31d5eaa3ed0eb6a65)
=> Alphabetize and add descrips to replacement commands.

userguide/sharing.rst
=> 11.2U4: Update VFS Module descriptions

userguide/intro.rst, userguide/tasks.rst
=> NAS-100140: Add "Bandwidth limit" field to Cloud Sync Options

userguide/intro.rst, userguide/tasks.rst
=> NAS-100390: Add Bandwidth Limit field to Cloud Sync Options

userguide/conf.py, userguide/install.rst, userguide/intro.rst, userguide/reporting.rst, userguide/sharing.rst, userguide/system.rst
=> NAS-101056 update mentions of USB devices and boot devices.

userguide/conf.py, userguide/install.rst, userguide/intro.rst, userguide/reporting.rst, userguide/sharing.rst, userguide/system.rst
=> NAS-101056 Fix text that was referring to USB devices other than for install only.

userguide/Makefile, userguide/conf.py
Removed broken patch from conf.py and add replacement to Makefile.
=> Fix broken arrow replacement for |menuselection|

userguide/system.rst
=> NAS-100097: Update "Show Text Console without Password Prompt" description

userguide/intro.rst, userguide/system.rst
cherry-pick PR #824 to 11.2-angular.
=> Work with Support to refine SED documentation.

userguide/system.rst
Cherry pick commits from PR #828 to 11.2-legacy.
=> Work with Support to refine SED docs

userguide/intro.rst, userguide/services.rst
=> NAS-100313: Remove "Dos charset" field from Services/SMB docs.

userguide/intro.rst, userguide/tasks.rst
=> NAS-100317: Add "Use --fast-list" field description to Cloud Sync Options table

userguide/services.rst
(cherry picked from commit 0742cc876ac81f2c3c9f1be54bfb48e4104146ee)
=> Add info and link for Zenoss and ZenPack.

userguide/virtualmachines.rst
=> NAS-100393: Add text explaining system virtualization error.

userguide/intro.rst, userguide/tasks.rst
Also add entry to intro
Identical to #848 
=> NAS-100394: Add "Exclude" to Cloud Sync Options table

userguide/intro.rst
=> NAS-100478: Add entry for new zettarepl tool.

userguide/Makefile, userguide/conf.py, userguide/snippets/alertevents.rst
Adjust conf.py and Makefile for the new icon.
HTML and PDF build test: no issues.
=>  NAS-100504: Add one-shot critical alert icon and description

userguide/system.rst
=> SED section: Work mav's comments into SED specs list.

userguide/intro.rst, userguide/tasks.rst
Add intro entry.
Description is identical to PR #884
=> NAS-100607: Add "Transfers" to Cloud Sync Options table:

userguide/quick.rst, userguide/tn_initial.rst
=> Update network reset message

userguide/intro.rst, userguide/tasks.rst
Add intro entry
Related image does NOT need to be updated.
=> NAS-100662: Add "Follow symlinks" checkbox to Cloud Sync Options table

userguide/sharing.rst
Add text about network discovery.
Do a general cleanup of text.
=> NAS-101129: Rework SMB share connection example/instructions.

userguide/accounts.rst
Port relevant changes from freenas/webui PR 2205
=> Update Account/Username field description.

userguide/services.rst
=> NAS-100952: Update SMB Services/Administrator Groups field name

userguide/services.rst
=> NAS-100724: Update NetBIOS Alias description in Global SMB Configuration Options table

userguide/intro.rst
=> NAS-100848: Add NUT IPv6 listen change to intro

userguide/sharing.rst
=> NAS-101096: Update "Path" description in "WebDAV Share Options" table

userguide/intro.rst
=> Add to intro the 3 new fields in Cloud Sync Tasks > ADD.

userguide/sharing.rst
=> NAS-100695: Add Samba user quota administration text 

userguide/system.rst
(cherry picked from commit acd5d5686c91bef3e29fa3f538477dadc4aba0fe)
=> Updated the "From Email" field descrip. to match the updated tool tip."

userguide/intro.rst
=> Mention the new "VERIFY CREDENTIAL" button in the intro.

userguide/intro.rst
=> Mentioned template jail creation in the intro.

userguide/intro.rst, userguide/services.rst
=> NAS-100100: Add zilstat field name and description to services.

userguide/intro.rst
Clean up intro to match current changes for 11.3.
=> NAS-100811: Remove "update/upgrade" intro entry and resort change list.

userguide/account.rst, userguide/shell.rst
Discovered many style and markup errors in shell.rst, so I've taken the opportunity to rewrite the section. Please review.
Port to angulargui and 11.2 branches when this text is ready
=> NAS-101064: Root user shell for default and rework shell.rst

userguide/services.rst
=> NAS-101168: Update "Hosts allow" and "Hosts deny" field descriptions.

userguide/intro.rst
Include link to tunable description in vt man page.
Please review and recommend further docs changes if any are needed.
HTML build test: no changes.
=> NAS-101176: Add new tunable to intro.

userguide/storage.rst
(cherry picked from commit 0facfd16ca56264099988224f26d392f1baf14a9)
=> NAS-100984 Mention the addition of the "Pool" column to Storage > Disks.

userguide/intro.rst, userguide/services.rst
=> NAS-101361: Update required fields in UPS Configuration Options table

userguide/conf.py, userguide/directoryservice.rst, userguide/system.rst
=> NAS-101373 Update all the redmine links to point to Jira.

userguide/storage.rst
=> NAS-100270: Fix typo

userguide/install.rst
=> NAS-101555:  Port vmware text improvements

userguide/install.rst
=> NAS-101555: Port vmware text improvements

userguide/services.rst
=> NAS-101490: Update UPS polling frequency tip.

userguide/intro.rst
=> Update intro to include new "Host Sync" field.

userguide/system.rst
(cherry picked from commit 3f661fc7afc456f337bceb08d4cdc0369c2910f7)
=> Catch the last of the "boot device" stragglers.

userguide/tn_initial.rst
TrueNAS build test: no issues.
=> NAS-100905: Fix typo

userguide/system.rst
=> Port changes from master to angulargui.

userguide/plugins.rst
=> NAS-100153 11.2angular

userguide/plugins.rst
(cherry picked from commit c3c66e357cb26da79cbeebab97cb987e6cdad31a)
=> NAS-100153 Revert the plugin creation instructions.

userguide/account.rst
(cherry picked from commit 496ff0155dfdcd8319f575706e718d2605516db0)
=> NAS-100799 Updated the description of creating user home directory.

userguide/system.rst
=> NAS-101587: Rewrite System Dataset text about storing system logs.

userguide/intro.rst
=> Update intro for new "Crash reporting" field.

userguide/intro.rst
=> Add new "Crash reporting" field to intro.

userguide/snippets/alertevents.rst
=> NAS-100322: Add new FC HBA alert to alertevents.rst

userguide/tn_hardware.rst
- Mention drive tray install recommendations and LED behaviors.
Cherry-pick to 11.1-truenas, 11.2-legacy, and angulargui branches when review is complete.
=> NAS-100148: Expand text about what is described in the BSGs.

userguide/system.rst
Reverts freenas/freenas-docs#1046
=> Revert "NAS-100716: Remove TrueNAS note about alert if system dataset is not …"

userguide/account.rst, userguide/network.rst
(cherry picked from commit 676bb58ce8f7ca5052f37a39b15c9ccc7ea080be)
=> TN review: account and network sections

userguide/directoryservice.rst
General review:
Check each link, command, file path, and screenshot. Update where necessary.
Sections:
Active Directory:
- Update menuselection
- Add missing link
- Clean up or add some markup syntax where needed.
LDAP:
- Clean up some text wrapping and link issues.
- Fix syntax error
NIS:
- No changes
Kerberos Sections:
- Update example slightly
- Small whitespace changes
=> NAS-101771: review directoryservice.rst for TN 11.2-U4.1

userguide/snippets/alertevents.rst
=> NAS-100410 : Add NVDIMM alert to alertevents.rst

userguide/jails.rst, userguide/storage.rst
Also, fixed a malformed table.
=> redmine 27384 fix (angulargui)

userguide/intro.rst
Added a U5 section to the intro.rst changelog area.
=> NAS-101545: Add FreeNAS changelog note about Python version update.

userguide/storage.rst
cherry-pick #1142 
Add temporary replacement image to storage-pools-add.png
=> NAS-101890: Add text about RESET LAYOUT button and rework SUGGEST LAYOUT button text

userguide/intro.rst, userguide/plugins.rst
Change is FreeNAS only: plugins.rst is not built for the TrueNAS guide.
Add intro changelog note
=> NAS-101971: Add asigra plugin to iX plugin index

userguide/intro.rst, userguide/plugins.rst
=> NAS-101971: Add Asigra to iX Plugin index

userguide/snippets/alertevents.rst
(cherry picked from commit 2fbff3a12d6813df8d4e3e6b297838738419e5f1)
=> redmine 27700 fix (11.2-angular)

userguide/intro.rst
(cherry picked from commit 2a84aa32519c4abe713d626f2de76f53fa8faa35)
=> NAS-101802 Add intro for updated AMD driver.

userguide/intro.rst, userguide/sharing.rst
cherry-pick #1137 and rework for 11.2-U5
=> NAS-101639: Add noacl VFS module to "Available VFS Modules" table

userguide/system.rst
=> NAS-101234: Add note about HA Carp behavior

userguide/intro.rst, userguide/sharing.rst
cherry-pick #1139 and remove intro entry
=> NAS-101639: Add noacl VFS module

userguide/intro.rst
(cherry picked from commit af5e8923d6c6ae2d081be69acdae42220409f9a5)
=> Move amd temp monitor to correct intro section

userguide/intro.rst, userguide/system.rst
Aside from the "Export pool Encryption Keys" docs, I also improved the appearance of some of the surrounding docs.
=>  NAS-102026 Add docs about "Export Pool Encryption Keys" setting. 

userguide/system.rst
cherry-pick #1146 to angulargui and do FreeNAS/TrueNAS HTML build tests: no issues.
=> NAS-101725: cherry-pick TrueNAS system dataset reboot text to angulargui

userguide/intro.rst
Add intro.rst entry for new field.
All other text and screenshots are addressed in PR #1141.
=> NAS-101177: Add 'Name' field to Replication Tasks

userguide/intro.rst
Add intro entry for new field.
All other docs needs are resolved in PR #1141
=> NAS-101274: Add 'Hold Pending Snapshots' field to replication tasks.

userguide/tn_intro.rst
https://redmine.ixsystems.com/issues/88182
Unified with snippets/contact.rst in bsgs repository.
Searched through repository and found one other instance of a Support phone number listed in tn_vcenter.rst, but adding this number does not appear to be relevent to that document.
=> 88182 and 88585: Add new Gold Support phone number and update Support hours

userguide/intro.rst
Add intro.rst entry
Text description is resolved in #1141
Image change is resolved in #1219
=> NAS-101277: Add 'Exclude' periodic snapshot task field docs

userguide/directoryservices.rst, userguide/intro.rst
Add note to intro.rst
Add entry to LDAP Configuration Options table
=> NAS-102112: Add entries for "Disable LDAP user/group cache" checkbox.

userguide/virtualmachines.rst
I also noticed that docker instructions were still in the guide.
I removed those as well.
=> NAS-102313 reindex entires in vm options table.

userguide/intro.rst, userguide/plugins.rst, userguide/storage.rst
=> NAS-102188: Rework dataset delete instructions and add intro entry

userguide/storage.rst
HTML test: no issues.
cherry-pick #1202 
Rework changes to match legacy UI.
=> NAS-102188: Update dataset delete description and add warning

userguide/intro.rst, userguide/tasks.rst
Investigate new field behavior in legacy UI and update 'Cloud Sync Options' table.
Synchronize with angulargui text where appropriate.
Add intro entry for new field and resort entries pertaining to Cloud Sync Tasks.
=> NAS-100129: Document 'Use --fast-list' checkbox.

userguide/storage.rst
This has a single build error until #1208 is merged. That PR has the necessary conf.py changes.
=> NAS-100084 update docs for updated snapshot page

userguide/snippets/alertevents.rst, userguide/system.rst
(cherry picked from commit f20f7d3f231aefa1a89f2820a0e6668c94775d67 #1235 )
=> NAS-101675 docs for email alert when proactive support ticket fails

userguide/system.rst
Tested with TrueNAS 11.2 internal build and FreeNAS 11.2-U5
Docs HTML build test: no issues.
=> NAS-102231: Review creating OneDrive cloud credential and update docs

userguide/snippets/alertevents.rst, userguide/system.rst
Cherry-pick all commits from #1235 
=> NAS-101675: docs for email alert when proactive support ticket fails

userguide/intro.rst, userguide/system.rst
Add intro entry with link to notice with more details.
=> NAS-102234: Remove Amazon Cloud Drive provider.

userguide/system.rst
Run through examples and verify they are still valid.
=> NAS-101108: Review ported SSH Connections text and update for legacy ui

userguide/tasks.rst
=> NAS-101110: Review UI fields that are part of Replication tasks

userguide/snippets/alertevents.rst
(cherry picked from commit 97d13444521e623afdc0064ef07485b108cdb58b #1233 )
=> NAS-101100 docs for snapshot failed alert

userguide/jails.rst
=> Plugin council task11.2angular

userguide/tasks.rst
=> NAS-101927: Update "Exclude" description in Periodic Snapshot Tasks

userguide/intro.rst
=> NAS-100740: Add note about converting SSH configs to SSH Keypair entries.

userguide/snippets/alertevents.rst
=> NAS-100959: new alert when cloud sync task fails.

userguide/tasks.rst
=> NAS-101026: Communicate that Cloud Sync tasks run sequentially

userguide/tn_vcenter.rst
Port #1238 and remove dashboard screenshot for now (not ready yet)
TrueNAS HTML build test: no issues related to this change
=> Port tn_vcenter improvements to angulargui branch

userguide/intro.rst
Cherry-pick Warren's change to 11.2-angular branch
=> Clarify Amazon Drive link (FreeNAS 11.2-U6 only)

userguide/system.rst
=> NAS-102231: Sync hubiC changes with #1270

userguide/intro.rst, userguide/services.rst
Add intro note for field changes.
HTML testing: no issues.
=> NAS-102239: Update fields in "Global SMB Options" table

userguide/virtualmachines.rst
This rest of this doc change is blocked by [NAS-102446](https://jira.ixsystems.com/browse/NAS-102446)
=> NAS-102328 docs for updated VM page

userguide/intro.rst
=> NAS-102259 intro entry for changes to SMB service options

userguide/intro.rst, userguide/jails.rst
=> NAS-100707 add intro entry for jail/plugin migration to iocage.

userguide/intro.rst
=> NAS-102339 intro entry for removing add to fav. checkbox

userguide/intro.rst
=> NAS-101273 Intro for 2 new snapshot tasks fields

userguide/intro.rst
=> NAS-102277 intro for theme selector removal and hostname move.

userguide/intro.rst
=> NAS-100141 intro entry for fetch method.

userguide/intro.rst
Include additional field in intro entry for PR #1189
=> NAS-100833 intro entry for new field in jail properties.

userguide/snippets/alertevents.rst
=> NAS-102201: Update scrub pause alert condition

userguide/intro.rst, userguide/system.rst
- Add intro entry for changed field.
- Update 'Cloud Credential Options' table
=> NAS-100121: Update System/Cloud Cred/SFTP field

userguide/intro.rst, userguide/snippets/alertevents.rst
=> NAS-101349 UPS events now use Alerts

userguide/storage.rst
- Fix one field description
- Add a couple use cases to the *Traverse* permission description.
=> NAS-101732: Review and update ACL manager text:

userguide/snippets/alertevents.rst
- Add TrueNAS specific item about SATADOM lifetime to alertevents.rst
=> NAS-100168: Satadom wear alert

userguide/storage.rst
(cherry picked from commit 6c092169434e4b1a1df65890a093e28ae4b7ee1b)
=> NAS-102396 Clarify wording for hot spares

userguide/sharing.rst
=> NAS-102023: Update ixnas VFS module description

userguide/intro.rst, userguide/tasks.rst
- Resort all entries in the list.
- Remove duplicate or obsolete entries.
- Change all menuselection roles to ref roles and add ref points.
- Fix a table error in tasks.rst
=> NAS-102683: Update change log for 11.3

userguide/tasks.rst
=> Port replication text updates from PR #1299 to angulargui branch

userguide/intro.rst
=> NAS-100345: Add intro note about new file.

userguide/directoryservices.rst
- Remove fruit and tdb2 idmap options.
- Remove connection error options (now automatic).
- Verify text matches information in reddit post.
- FreeNAS HTML build test: no issues.
=> NAS-101537: Review DirectoryServices docs

userguide/plugins.rst
These descriptions were collaboratively worked on by marketing and me. Just need a merge.
=> NAS-102537 sync userguide plugin descrips with INDEX file descrips

userguide/system.rst
Port #1368 for 11.2U6 release.
=> NAS-102266: Port VIP/VHID description changes to 11.2-legacy

userguide/directoryservices.rst, userguide/intro.rst
=> NAS-100091: Update LDAP hostname field description.

userguide/intro.rst
Updated intro entry with regard to [dru's comment](https://jira.ixsystems.com/browse/NAS-101516?focusedCommentId=97528&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-97528)
=> NAS-101516 Clarify intro for remove periodic notification user

userguide/intro.rst
=> NAS-101537: Add intro entries for removed fields.

userguide/tasks.rst
Remove redundancy from PR #1313
=> NAS-101569 remove redundancy of manual cron task email

userguide/tasks.rst
The intro entry needed no change.
=> update replication task log tense

userguide/intro.rst, userguide/storage.rst
=> NAS-100225: Add text to Import Disk section about viewing log.

userguide/intro.rst
- Investigate system.rst and alertevents.rst and determine no further changes are needed.
=> NAS-100431: Add intro entry about periodic alert backend switch.

userguide/intro.rst
=> NAS-100348 add intro entry for removal of Default Permissions

userguide/zfsprimer.rst
=> NAS-102868: Remove pool space recommendation from ZFS Primer.

userguide/intro.rst
=> NAS-102798 intro for removal of netbios name and alias.

userguide/intro.rst, userguide/services.rst
I also moved an intro entry to more appropriate spot.
=> NAS-102252 doc removal of asigra from service page

userguide/plugins.rst
Updated the asigra description with regard to [Warren's feedback](https://github.com/freenas/freenas-docs/pull/1358/files#r313090018).
=> Update asigra plugin descrip with feedback.

userguide/intro.rst, userguide/storage.rst
- Port field descriptions from UI help text.
- Add intro entry.
=> NAS-100710: Add new fields to Disk Options table.

userguide/network.rst
- Update TrueNAS field names to match UI.
- Review text and image to verify no further changes needed.
=> NAS-100747: Review/update TrueNAS Network/Global Configuration text.

userguide/install.rst, userguide/intro.rst
- Add text about behavior and restrictions in install.rst
- Add note to intro changelog
=> NAS-100372: Add text about automatic swap partitions

userguide/system.rst
Ported PR #1375 to 11.2-legacy
=> Cherry-pick docs for location of ssh keys

userguide/sharing.rst
- Add note with link to Apple Time Machine docs
- Update example descriptive text
- HTML build test: no issues
=> NAS-102912: Update 'Client Time Machine Configuration' subsection

userguide/storage.rst
=> NAS-102152: Add caution about powering on VMs

userguide/storage.rst
- html build testing: no issues
=> NAS-102152: update text a little from offline feedback.

userguide/intro.rst, userguide/sharing.rst
- Sync with current available modules
- Compact table
=> NAS-101293: Update Available VFS Modules table

userguide/system.rst
(cherry picked from commit 631bdae0ccd1afb781a579039c56ae87fbc717d4)
=> sync endpoint URL doc descrip with updated helptext

userguide/system.rst
- Add links to rclone documentation.
- Combine/Expand Google Cloud Storage description.
- Compact the table.
- html testing: no issues.
=> NAS-102240: Update 'Cloud Credential Options' table

userguide/system.rst
- HTML build testing: no issues
=> NAS-102300: Add text about private attachments

userguide/sharing.rst
- Clean up a couple obsolete bits of text
=> NAS-102632: Add text about ACL editing to SMB Sharing section

userguide/network.rst
- Backport note update to master TrueNAS guide.
=>  NAS-102193: Update note about edit/delete TrueNAS HA interfaces

userguide/network.rst
- Backport note update to 11.2 TrueNAS guide.
=> NAS-102193: Update note about edit/delete TrueNAS HA interfaces

userguide/system.rst
=> NAS-102300: Remove reference to obsolete "document vault"

userguide/storage.rst
=> NAS-102739: Update 'Create Dataset' Share Type field behavior

userguide/intro.rst, userguide/snippets/alertevents.rst, userguide/tasks.rst
- Add intro entry for new alerts
- Update "quiet" field description and compact 'Rsync Configuration Options' table.
- Add rsync status alerts to alert list.
=> NAS-102813: Rsync task status alerts

userguide/jails.rst
- Clean up some descriptive text of Jail Wizard options.
- Compact 'Basic Properties' table.
- Review related image: no changes necessary
=> NAS-102924: Update Jails/'Release' field description.

userguide/intro.rst, userguide/jails.rst
- Add text to Jail documentation about iocage log file
- Add intro entry
- HTML build test: no issues
=> NAS-100391: iocage log file

userguide/storage.rst
This change is with regard to [dru's comment](https://jira.ixsystems.com/browse/NAS-102865?focusedCommentId=98248&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-98248)
=> NAS-102865 add ifdef for trunas and freenas about hot-swap drive bays

userguide/system.rst
This reverts commit 3f4545439627faa88dee16004d678f26cd201abd.
=> Revert "NAS-102850: review update 1"

userguide/intro.rst, userguide/snippets/usingui.rst, userguide/tn_intro.rst
- Update section levels to match the rest of the document
- Add the 'usingui.rst' snippet in the same relative location as the FN guide
- TN HTML build test: no issues.
=> NAS-102301: Update tn_intro.rst

userguide/system.rst
=> NAS-101816: Small update to CA/'Sign CSR' option description.

userguide/services.rst
Adjust description to show field is looking for static IP Addresses.
=> NAS-102256: Update Bind IP Addresses description.

userguide/intro.rst, userguide/sharing.rst
Update documentation to match what is presented in the UI.
=> NAS-101293: Rename VFS modules to VFS objects:

userguide/jails.rst
=> NAS-102924: Review update 1

userguide/snippets/usingui.rst, userguide/tasks.rst
- Clean up some of the related text in the Scrub Tasks section
- Update Usingui calendar description to include reference to scrub tasks section
=> NAS-102931: Rewrite 'Threshold days' description.

userguide/system.rst
=> NAS-103052: System/General - Update note about restarting web service

userguide/storage.rst
=> NAS-102739: Update from testing notes

userguide/intro.rst
- Remove unneeded reference to settings/preferences as it is no longer applicable.
=> Fix angulargui build warning

userguide/intro.rst, userguide/tasks.rst
This change address [dru's comment](https://jira.ixsystems.com/browse/NAS-102955?focusedCommentId=99026&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-99026) and the fact that half of the changes in PR #1495 disappeared.
=> Nas 102955 angulargui

userguide/tasks.rst
- Update Schedule description
- Small cleanups to text
- TODO: synchronize with UI help text EDIT: https://github.com/freenas/webui/pull/2772
- HTML build test: no issues
=> NAS-101272: Review Advanced Replication Creation field descriptions

userguide/system.rst
- Move an out of place sentence to the correct location
=> NAS-103111: Update TrueNAS Support docs to mention reloading UI.

userguide/system.rst
- Proposing a small change to SED description. Not sure if a docs change is really needed for this ticket.
=> NAS-100995: Unlock SED before including in pool

userguide/intro.rst, userguide/system.rst
- Synchronize with https://github.com/freenas/webui/pull/2766 when it is approved and merged.
=> NAS-103089: Document 'Region' S3 Cloud Cred. field

userguide/system.rst
- Remove VHID numbers recommendation.
=> NAS-102266: Update from Releng feedback

userguide/system.rst
=> NAS-102266: Update from Releng feeback

userguide/intro.rst
=> NAS-103188 intro entry for new/removed AD,LDAP fields.

userguide/tn_eula.rst
Ticket: #34044
Cherry-pick this latest commit to the EULA to the angulargui branch.
Removed a couple unneeded whitespaces.
EDIT: https://jira.ixsystems.com/browse/NAS-102920
=> Update to updated EULA (cherry-pick from master).

userguide/system.rst
=> NAS-101139: Update OAuth text for cloud credentials

userguide/sharing.rst
=> NAS-103195: sync noacl description with 11.2-legacy branch

userguide/tasks.rst
This change is in regard to [dru's comment](https://jira.ixsystems.com/browse/NAS-102955?focusedCommentId=100819&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-100819)
=> NAS-102955 Update description of Rsync path checking.

userguide/system.rst
=> NAS-103963: Sync up 11.2 Backblaze B2 cloud sync cred fields with docs.

userguide/system.rst
- Port over applicable text improvements
=> NAS-101139: Resync 11.2-legacy Cloud Provider text with angular

userguide/intro.rst, userguide/system.rst
- Add intro entry.
- Update fields to reflect U7.
- Backport applicable text improvements from angulargui branch.
=> NAS-101139: Update OAuth docs for 11.2-U7

userguide/services.rst
Reminder to sync the final text with the webui repo.
=> NAS-103770: Update `Allow Local User Login` description

userguide/settings.rst
- Match current behavior in 11.3 Nightlies
=> NAS-103774: Update Settings/Change Password text

userguide/tasks.rst
- Retest the behavior and update the Remote Encryption, Filename Encryption, Encryption Password, and Encryption Salt descriptions.
- Sync final text with UI help text.
=> NAS-103773: Review and update encryption options for Cloud Sync Tasks.

userguide/tasks.rst
=> NAS-103773: resync text across branches

userguide/storage.rst
- Adapted from https://www.reddit.com/r/freenas/comments/dy3unu/how_to_have_the_permissions_of_new_files/f87makn/?context=3
=> DOCS-78: Add text about ACL inheritance

userguide/intro.rst
=> NAS-101498: Add description of parallel replication behavior to intro.

userguide/system.rst
- Add text describing how to create a new SSH key for the SFTP credential.
- Needs webui sync
=> NAS-103508: Update description of System/Cloud Credentials/SFTP fields

userguide/system.rst
=> NAS-103956 add docs for reverting/changing SED drive data and passwords.

userguide/system.rst
- Update credential description with correct configuration procedure.
Webui helptext needs an update.
=> NAS-103535: Update Onedrive credential docs.

userguide/intro.rst, userguide/services.rst
- Add text about USB auto option.
- Break down a tip box into regular section text.
- Add intro entry about new option.
Port description improvement to the UI help text.
=> NAS-103592: Update Services/UPS/Port or Hostname field description

userguide/system.rst
- Might still be a little chunky, but seems more clear which controller is updated last.
=> DOCS-88: Clarify HA update controller order.

userguide/tasks.rst
- Add note about resetting the transfer mode to COPY when the direction is changed.
Sync with webui
=> NAS-103716: Update Tasks/Cloud Sync Tasks/Direction description

userguide/jails.rst
=> NAS-104007 update docs for new iocage pool activation dialog.

userguide/intro.rst, userguide/network.rst
=>  NAS-103595: Update procedure to temporarily apply network settings and then permanantly apply them.

userguide/intro.rst, userguide/network.rst
Add intro entry for new checkbox
Add entry to Interface Configuration Options table describing the option and provide a warning about performance impact.
TODO: Port field name change and description to the Angular UI
=> NAS-104139: Document NIC hardware offloading option.

userguide/virtualmachines.rst
=> NAS-103557 Add docs for human readable field in VMs.

userguide/sharing.rst
- Add internal reference point for iSCSI wizard and fix Authorized Access section title.
- Update description of setting up a Discovery Auth Group in the wizard.
- HTMl build test: no issues
=> NAS-103854: Update iSCSI Wizard Portal page text:

userguide/jails.rst
=> NAS-103887 add docs for saving iocage config to new boot environments.

userguide/tasks.rst
- Retest Rep. Wizard behavior and update text about choosing datasets for replication.
=> NAS-103807: Update Replication Wizard snapshot process:

userguide/storage.rst
=> NAS-103604 Update process to destroy pool and data in docs

userguide/plugins.rst
=> NAS-103439 docs for displaying plugin Admin Portals.

userguide/jails.rst
=> NAS-103887 Clarify docs on jail config backup location.

userguide/jails.rst, userguide/plugins.rst
=> NAS-104009: Sync update jail/plugin "Name" description from UI text.

userguide/jails.rst
=> NAS-103887 clarify jail/plugin config backup.

userguide/conf.py, userguide/plugins.rst, userguide/snippets/usingui.rst, userguide/tasks.rst, userguide/virtualmachines.rst
Also add a human readable section so that it can be referenced when writing about human readable fields.
**11.3-BETA1** change.
=> NAS-103404 add docs for human readable field "memory" in VMs.

userguide/intro.rst, userguide/system.rst
- Add intro entry documenting the change.
=> DOCS-109: Remove show tracebacks option from System/Advanced

userguide/jails.rst, userguide/virtualmachines.rst
=> DOCS-113: Add recommendations about Hardware Offload to jails and VMs.

userguide/sharing.rst
- Add text about IPv6 wildcards.
- HTML/TrueNAS HTML build test: no issues.
=> DOCS-116: Update iSCSI Portal IP Addresses descriptions.

userguide/intro.rst, userguide/snippets/alertevents.rst
- Add intro entry for new field in System/Alert Settings
- Add generic text about possible alert condition to snippets/alertevents.rst
=> DOCS-114: New alert for slow pool I/O

userguide/intro.rst, userguide/storage.rst
- Update SED Password description to include help text.
- Add entry for new Clear SED Password checkbox using the current UI help text.
- Update intro entry for Storage/Disks/Edit changes.
=> DOCS-121: Update Storage/Disks options

userguide/zfsprimer.rst
=> DOCS-122: remove outdated link from ZFS primer

userguide/contribute.rst
- Update procedures to incorporate forking the webui repo and opening PRs from the forked repo.
=> DOCS-119: update translation instructions

userguide/services.rst
=> NAS-104563: Add recommendation for disabling SSH "none" cipher.

userguide/tasks.rst
=> Add Amazon S3 docs link to Cloud sync notes.

userguide/conf.py, userguide/sharing.rst, userguide/system.rst
- Update conf.py to show 11.3 guide is a review draft.
- Make a few small refinements to text.
- Move the Block (iSCSI) section to match the menu order in the UI.
- TrueNAS html build test: no issues.
=> DOCS-129: review closed TrueNAS 11.3 tickets and update 11.3 guide

userguide/system.rst
=> DOCS-130 small docs change for HA review.

userguide/intro.rst
=> Brand cleanup

userguide/conf.py, userguide/tn_intro.rst
- TN html build test: no issues.
=> DOCS-202: Rename 11.3 TN guide and add note

userguide/conf.py
=> Update copyright year for minimal 11.2-U8 release

userguide/sharing.rst
The docs were present for the related ticket. I just tested behavior of
fields and added more info for clarification.
=> DOCS-287 docs were there. Just a clarification.

userguide/network.rst
- Investigate and expand the description for Channel, Password, and add an IDENTIFY LIGHT entry.
=> DOCS-283: Expand docs for Network/IPMI:

userguide/tasks.rst
=> DOCS-302: update Exclude Child Datasets field description

userguide/tasks.rst
Ported from https://github.com/freenas/webui/pull/3727
=> NAS-105113: Update Replication Source and Destination text

userguide/sharing.rst
Very minor change. The option to select a periodic snapshot within the share config menu has gone away. That is now being done automatically.
=> Update docs for changes to SMB/periodic SS.

userguide/tasks.rst
=> DOCS-195: Add Description field to Init/Shutdown Script options.

userguide/storage.rst
- investigation and prep work for changes to adding vdevs to a pool.
=> DOCS-227: Storage reworks to describe expanding a pool.

userguide/accounts.rst
branch name should be nas-105683
=> NAS-105683 update primary group description.

userguide/services.rst
(cherry picked from commit 20affd93143b896547bfaabb28946b7a2094fee1)
=> NAS-100620 Expand the S3 service docs.

userguide/directoryservices.rst
=> NAS-106011: Remove obsolete info from AD docs

userguide/directoryservices.rst
=> NAS-106012: Clean up obsolete LDAP docs

userguide/intro.rst, userguide/jails.rst, userguide/plugins.rst, userguide/services.rst, userguide/storage.rst, userguide/system.rst, userguide/tasks.rst, userguide/ui_login.rst, userguide/virtualmachines.rst
cherry-pick commits and rework where needed.
=> DOCS-426: port docs improvements to 12.0 guide

userguide/conf.py, userguide/intro.rst
=> DOCS-549: TN 11.3-U2.2 hotfix

userguide/sharing.rst
(cherry picked from commit 8ae764549d817fc2852e83ba9b39f858a42995f7)
=> DOCS-106099 host allow and deny doc improvement.

userguide/conf.py
- review "Done" tickets for docs impact (none assessed)
- Update Guide version for TrueNAS release.
=> DOCS-537: Prepare guide for TrueNAS 11.3-U3.2 release

userguide/tasks.rst
Sync up note about overlapping schedules and do a little maintenance on the text.
=> NAS-106251: Cron Task text updates

userguide/tasks.rst
Sync up note about overlapping schedules and do a little maintenance on the text.
=> NAS-106251: Cron Task text updates (11.3 cherry-pick)
