freenas/freenas-docs

userguide/conf.py
- Altered the patch to use unicode numbers instead of text names.
- Changed the arrow symbol to be as pdf generation friendly as possible.
=> Updated :menuselection: arrow replacement patch:

README.md
The current headings aren't in markdown format so this updates them so they render correctly.
=> Reformat markdown headings in README.md

userguide/services.rst, userguide/sharing.rst
In addition to these, enabling NTLMv1 auth is now handled by an checkbox in the UI under Services->SMB. No need to add an aux parameter.
=> Updates regarding SMB shares

userguide/directoryservice.rst
This idmap backend was purged from Samba. See https://bugs.freenas.org/issues/25500
=> Kill idmap_adex with fire

userguide/storage.rst
1) Link to a more exact description about GELI key management.
People using encryption (and managing its various keys) are likely to be the kind of people who will want exact details how keys are stored and managed. While they could Google GELI, that won't explain how %brand% uses and stores them, and is a lot to read through. However there's a nice and concise forum post which summarises it nicely and worth linking to for that info.....
2) Move "encryption performance" to its own small heading below the bullet list
Performance is always a question/concern with encryption. This keeps the main bullet list short and "to the point", and pulls the 1 or 2 bullets on performance to below the list, which (to me) flows much better.
3) Merge "encrypted on write" and "decrypted on fly during read" …
=> Various edits to the "encryption" header text

userguide/services.rst, userguide/tasks.rst
See https://redmine.ixsystems.com/issues/21374 . 
1) A lot of the detail under rsync tasks was really more about rsync background, and overlapped with the service page.  So I've collected all the rsync background, basics and terminology at "Rsync service" for user ease, which simplifies the "tasks" page considerably.
2) A lot of the text on Rsync wasn't helpful at all. (See redmine link above). I've tried to tune it a little without adding much or getting into detailed config, so a user gets a better idea of this valuable service and the terminology used by *NAS.
3) The guide doesn't cover two rather crucial "need to know"s about Rsync - It doesn't encrypt data, so use some kind of secure transport (SSH) across insecure networks or internet if this matters, and use a minimally privileged …
=> Rsync service + tasks

userguide/account.rst, userguide/api.rst, userguide/cli.rst, userguide/contribute.rst, userguide/install.rst, userguide/intro.rst, userguide/jails.rst, userguide/network.rst, userguide/plugins.rst, userguide/processes.rst, userguide/quick.rst, userguide/reporting.rst, userguide/services.rst, userguide/sharing.rst, userguide/snippets/alertevents.rst, userguide/snippets/unified-storage-array.rst, userguide/storage.rst, userguide/support.rst, userguide/system.rst, userguide/tasks.rst, userguide/tn_cinder.rst, userguide/tn_initial.rst, userguide/tn_options.rst, userguide/tn_vcenter.rst, userguide/vaai.rst, userguide/vms.rst, userguide/wizard.rst, userguide/zfsprimer.rst
Exhaustive review of all links contained in every .rst file to fix broken links,
update http -> https addresses, and update link syntax to use two underscores (`_ -> `__).
Conducted link testing with both make linkcheck and manually.
There are a few "false positive" links remaining that display an error or warning, but do actually work properly.
HTML build testing for both FreeNAS and TrueNAS guides: no issues.
=> Link review and syntax update:

userguide/storage.rst
This is pretty important info for anyone who needs to search their snapshots - "previous versions" doesn't cut it when searching. See eg, redmine #27255 last couple of posts, and feature request #29381
=> Browsing a snapshot collection

userguide/snippets/pathlengths.rst
This is important so a user can understand what exact path components are measured, when considering if a snapshot will be accessible, or fixing a snapshot that isn't accessible.
As Dru noted on forum, it isn't well documented ( https://forums.freenas.org/index.php?threads/snapshot-mounting-limits-clarification-of-freenas-guide.60633 ).
=> Clarify 88 byte limit with examples

userguide/jails.rst
Made a few changes related to:
- Standards we're using for documentation (use |ui-add| when telling the user to click one of the + buttons in the ui.)
- Update text to reflect the exact name of an element in the UI (Advanced Jail Creation button)
- Clarify new jail dataset creation a bit.
- I've only looked through line 103 so far.
=> Review/update the first part of jails.rst

userguide/vaai.rst
-This section did not change in the UI so it was left mostly the same.
-Removed "running" from this sentence: "*Stun* pauses running virtual machines when a pool runs out of space" as it is redundant. If I ever happen to come across any lazier virtual machines that prefer walking, I'll update this section accordingly.  
-Changed one sentence from passive to active - s/threshold can be/ threshold is.
-Removed weird hyphen placement.
=> Reviewed vaai.rst for errors.

userguide/storage.rst
Finally finished reviewing this massive section!
-Went through the entire document to verify the instructions match up with the UI, with the exception of the import geli-encrypted disk and view multi path sections. 
- Added too many of our new |ui-settings|, |ui-options|, |ui-options| icons.
- Removed "the following" references so Warren doesn't follow up with me. 
- Removed "you" and "you" references.
- Fixed incorrect use of possessives: disk's/dataset's/pool's.
- Replace "checkboxes" with "options".
- Replace "check" with "set" or "select" . 
- Fix minor typos like "iterms per page".
- Remove "it is recommended".
- Passed the build test with no errors.
- Checked for whitespaces with git dif --check
=> Reviewed storage.rst:

userguide/jails.rst
Add in the correct output of `iocage destroy`.
Test other iocage command line examples.
https://redmine.ixsystems.com/issues/35113
=> Fix `iocage destroy` example: (Redmine issue #35113)

userguide/jails.rst
- Update jail name in example to match the command.
- HTML build testing: no issues
- https://redmine.ixsystems.com/issues/35113
=> Fix name error in `iocage destroy` example (Redmine issue #35113):

userguide/shell.rst
Tested the ctrl + c and ctrl + v options to copy and paste in the Shell console in Firefox and they didn't work. Ctrl + c will actually cancel any processes running so it is important that we don't tell users to do that. If you want to copy any text in the shell console in Firefox, the only way to do that is by using the edit option in Firefox's open menu in the top right. I've updated the docs accordingly. 
Passed build test with no errors.
=> Reviewed the shell.rst:

userguide/sharing.rst
Explain /etc/exports does not act like an ACL so the network
and host must be unique per share and per filesystem or directory
=> Update NFS share rules

userguide/sharing.rst
Explain /etc/exports does not act like an ACL so the network
and host must be unique per share and per filesystem or directory
=> Update NFS Share rules on master

userguide/storage.rst
- [38400](https://redmine.ixsystems.com/issues/38400)
- Reorganize entries to reflect their placement in the UI.
- Add missing "Sync" entry.
- Add more explanatory text to the Compression level and ZFS Deduplication entries.
- Add "Advanced Mode" column and indicate "Block size" is an Advanced setting.
- Add another tabularcolumns entry and reset the values.
=> Update "zvol Configuration Options" table:

userguide/jails.rst
- Review GitHub commit history and verify iocage isn't tagged before FN 11.0
- Update text to reflect that iocage was added with FN 11.0
=> Fix error concerning iocage inclusion:

userguide/system.rst
Certificates in ticket #34927
- The view button was added to more options for existing CAs and Certificates. I updated the docs to reflect this change. 
- Passed build test no errors
- Tested this on FreeNAS-11.2-MASTER-201807230852.
=> Updated system.rst based on changes made to CAs and 

userguide/sharing.rst
- Add text to description of "Disable Physical Block Size Reporting" field to note that setting can avoid warning spam with ESXi.
- Add link to relevant blog post.
- Fix a couple empty space issues.
- Change will also be ported to master branch.
=> Fix 34384 [angulargui]:

userguide/directoryservice.rst
- Update the example to match the syntax outlined in 38791.
- Rework the surrounding text to match the example.
- Add external links to keytab documentation.
- Will port these changes to angulargui branch
=> Rework Kerberos Keytab generation example and text:

userguide/account.rst, userguide/storage.rst, userguide/tasks.rst
- 34077: tables in Account/Users, Storage/Disks, and Tasks/Cron Jobs have customizable columns.
- Add descriptions in each relevant chapter to reflect this change.
=> Add text descriptions of customizing tables:

userguide/services.rst
- 26157
- Add text to "Disk" field description of S3 Configuration Options table to describe the permissions changes that happens when a directory is added here.
=> Add text describing permissions changes by the S3 service:

userguide/services.rst
- 36968
- Add text warnings that only alphanumeric characters are allowed in the above mentioned fields.
=> Describe input limitations of the S3 Access Key and Secret Key fields.

userguide/vms.rst
- Move a bit of descriptive text above its related screenshot.
- Add an admonition box to notify the reader about the UI showing errors on VM start failure.
- UI specific: no changes for master branch.
=> Add note about the UI showing an error when a VM doesn't start:

userguide/vms.rst
- Add an admonition box explaining that a VNC device cannot be added to a VM when one is created during the VM creation process.
=> Add explanation about existing VNC devices.

userguide/conf.py
- This fixes all missing bold and italic rendering for PDF generation.
- PDF build test: no issues.
- Note: fontspec documentation requires manually setting the bold, italic, and bolditalic fonts when the main font is called by filename. See https://mirror.hmc.edu/ctan/macros/xetex/latex/fontspec/fontspec.pdf for more details.
=> Add Bold, Italic, and BoldItalic Font support:

userguide/system.rst
This was a fix for [ticket 29106](https://redmine.ixsystems.com/issues/29106).
=> Removed the note saying encrypted pools weren't displayed in dropdown.

userguide/system.rst
Tested on master branch. In the old UI an encrypted, locked volume did not show up in the system data set drop down. This is a master branch change only.
=> Updated the note about locked volumes not showing in system dataset.

userguide/jails.rst
=> Removed sentence about not being able to rename jail in UI. 

userguide/tasks.rst
Add text describing seeing download logs for a successful or failed cloud sync task.
Master branch handbook needs this as well.
HTML test: no issues
=> Update documentation to reflect change from ticket 27756.

userguide/conf.py, userguide/services.rst
review and fix a few small things, add new text replacement to conf.py:
- Text replacement is in support of upcoming change to using table view as default.
- Clean up some text, fix extra lines in a couple spots.
=> Add text about confirmation dialog when stopping a service,

userguide/system.rst
Check related tables to verify Identifier entry is correct.
=> Add missing comma to Identifier entry in Importing a CA Options table

userguide/conf.py, userguide/vms.rst
Retest, review, and rewrite instructions for creating and configuring a Docker Host and setting up RancherOS.
Adjust some terminology in the wider VMs.rst chapter.
Remove requirement for the httpdomain extension in the conf.py.
This will need to be backported into the master branch.
=> Rewrite Docker Host instructions

userguide/storage.rst
Corrected typo 'Rnabled' to 'Enabled' in the Disk Options table
=> Fix typo under Storage > View Disks

userguide/vms.rst
- These changes are in response to bug #40444
- The ability to select a disk type (VirtIO and AHCI) was added to the VM Wizard in the UI so I updated the  VM Options Wizard table to reflect this change. 
- Updated "Select datastore" to "Select pool or dataset" to match the current name of the field in the UI.
- Passed build test with no issue. 
@wblock Just as a side note, I noticed we refer to screen # in the table below, but did we consider numbering the wizard pages in UI as well?
=> Updated docs to reflect new UI changes

userguide/intro.rst, userguide/system.rst
- I removed the enable power saving option from the Advanced Configuration Settings table. 
- Passed build tests with no errors.
- This is in response to Bug #49398
=> The enable power saving daemon checkbox was removed from the UI 

userguide/sharing.rst
- Rework LUN ID table entry to reflect using a value of 0.
- Replace Target/Extents terminology with Associated Targets. New UI doesn't use "Target/Extents".
=> Update LUN ID and Target/Extent terminology:

userguide/system.rst
- We also generate multiple files now instead so I updated the docs to include that as well.
- This is in response to bug #51656.
- Passed build test with no issues.
=> We are no longer using ASCII files to save debugs so I updated the docs.

userguide/storage.rst
permissions after configuring an SMB share with ACLs.
Fixed :ref: formatting error.
This is in response to bug #48184
Passed build test.
Text approved by Andrew W.
=> Added a warning for Windows users to avoid changing back to Unix 

userguide/jails.rst
a mount point while a jail is running so I clarified that in the docs.
Passed build test with no issues.
Related to https://redmine.ixsystems.com/issues/47184
=> We added some warning messages in the UI about not being able to delete, edit, or add 

userguide/system.rst
- Port relevant change to a more "version agnostic" description of update trains.
- Update some blocks of text that were changed in angulargui branch but didn't appear to get ported to master branch.
- Clean up some redundant text.
- Slight rework to the admonition boxes in the section.
- Change the ifdef FreeNAS/ifdef TrueNAS sections to better fit the text.
=> Port changes from 40940-docs-angular, with reworks:

userguide/storage.rst
Replace the warning with another bullet point explaining when attached L2ARC drives are encrypted.
=> 27878: Fix warning about L2ARC encryption

userguide/snippets/es12.rst
- I removed the sentences that mentioned powering off the xseries as suggested by Bill. 
- Bill O'Hanlon reviewed this section and said the procedure is right and does not need to change other than removing those two sentences. 
- This is in response to https://redmine.ixsystems.com/issues/57294
=> The TrueNAS unit can remain on while the expansion shelf is connected.

userguide/intro.rst, userguide/virtualmachines.rst
- Add entry to intro.rst about the new functionality of ifconfig.
- Add tip box to the virtual machines/network interfaces section explaining how to see which interface is associated with a VM.
- Changes need a port to master branch.
=> 68473: Add note about tap interfaces and virtual machines.

userguide/conf.py, userguide/intro.rst, userguide/snippets/copyright.rst, userguide/tn_intro.rst
Define new |copyright-year| substitution in conf.py and use it where necessary in the FreeNAS/TrueNAS guides.
FreeNAS/TrueNAS HTML test: no issues.
=> Copyright year substitution:

userguide/directoryservices.rst, userguide/intro.rst
Rework entry to indicate password is only required the first time a domain is configured.
Add entry in intro.rst to explain the change.
Change is new UI specific. No port to other branches is necessary.
=> 59397: Update entry for Domain Account Password in directoryservices.rst

userguide/directoryservices.rst
- Update entry to indicate choosing the blank option clears a saved certificate.
- Determine this is fixing a bug to bring feature parity with old UI. No intro.rst entry needed.
- This text applies to the legacy ui documented in both the master and freenas/11.1-stable branches. PR will be ported to each branch.
=> 60792: Update Certificate field in directoryservices.rst/AD section

userguide/directoryservices.rst, userguide/system.rst, userguide/truenas.rst
Fix the blockers that were preventing an HTML build of the TrueNAS guide from completing:
- directoryservices.rst name mismatch.
- Removal of wizard.rst from the angular guide.
- Not enough space for a %brand% replacement inside a table.
Fixed the TrueNAS build warnings in system.rst:
- Remove additional #endif freenas that had no starting definition.
- Fix up a reference point that is not included in the Truenas guide.
`make TAG=truenas html` works now, but there are 19 warnings generated.
=> Fix building TrueNAS guide

userguide/intro.rst
Investigation of storage.rst and reporting.rst shows no changes needed.
Investigation of angulargui branch and 11.1-stable branch shows change not reflected in either FreeNAS version.
=> Add entry reflecting l2arc size reporting change to intro.

userguide/jails.rst
Doc queue item 28 (no Redmine ticket): https://forums.freenas.org/index.php?threads/there-is-something-missing-in-the-documentation-that-might-make-sense-to-mention.72480/#post-501869
Add simple example of using logout to exit a jail console.
=> FreeNAS Forum suggestion: Add example of exiting iocage jail console

userguide/system.rst
Adjust the relevant table entries in system.rst.
=> 66925: Add minimum bit lengths to CA and Certificate Private Key entries

userguide/intro.rst
- Investigate the rest of the guide and did not find any other relevant text.
=> 33141: Add entry to intro about the removed collectd IPMI plugin.

userguide/intro.rst, userguide/snippets/alertevents.rst
Add entries in intro.rst and snippets/alertevents.rst for the new alert.
=> 45398: Add syslog-ng alert

userguide/virtualmachines.rst
Investigate notes in [27301](https://redmine.ixsystems.com/issues/23701#note-15), [28580](https://redmine.ixsystems.com/issues/28580#note-3), [23990](https://redmine.ixsystems.com/issues/23990#note-9), and [23794](https://redmine.ixsystems.com/issues/23794#note-18) and add a short recommendation to use AHCI disks for VMs using a Windows OS.
=> Doc Queue Item 1: Add AHCI disk recommendation for VMs with a Windows OS

userguide/intro.rst, userguide/sharing.rst
- Add entry in intro.rst/U2 section.
- Add a bit of text at the end of the sharing.rst/Block (iSCSI)/Extents section
explaining where the NAA is shown.
- HTML build test: no issues
=> 50321: Add text about new NAA column in Sharing/iSCSI/Extents:

userguide/system.rst
(from https://forums.freenas.org/index.php?threads/sed-password.73170/)
- Adjust terminology to reflect that the SED is locked until the administrator "takes ownership" by setting the password.
- This should avoid implying the device is modifying/removing existing data.
=> Doc queue item 77: FreeNAS forum: Clarify initial SED password

userguide/intro.rst
Rename not present in legacy UI. No master PR needed.
Searched angulargui branch docs: no remaining instances of "Wait to Boot" option found.
=> 62712: Add entry to intro.rst for rename of VNC "Wait to Boot" option.

userguide/sharing.rst
From FreeNAS forums: https://forums.freenas.org/index.php?threads/guest-access-in-smb2-disabled-in-windows-10.72097/
Added note to sharing.rst/SMB/Unauthenticated Access section explaining SMB2 guest access is disabled in certain versions of Windows. Added link to the Microsoft security notice.
=> Doc queue item 31: Add note about SMB2 guest access disabled in Windows.

userguide/storage.rst
storage.rst: Remove admonition box and work its text into the regular section text.
Add text explaining the disk filter fields in the pool create screen support PCRE regex.
Add link to PCRE syntax reference and a simple example.
Disk filtering appears to be new UI only, so no master branch PR.
=> Doc Queue item 4: Add text about PCRE regex support to filter disks.

userguide/conf.py, userguide/virtualmachines.rst
Replacement defined in conf.py.
Rework virtualmachines.rst to use the replacement.
Fix some rough spots caused by the replacement.
Fix a couple visual errors by swapping menuselection directives with guilabel.
=> 72755 (11.2-U3): Define a Docker Host replacement

userguide/conf.py, userguide/virtualmachines.rst
Reverts freenas/freenas-docs#706
This needs to wait for 11.2-U3. I'm going to reopen the PR and label it with "don't merge yet"
=> Revert "72755 (11.2-U3): Define a Docker Host replacement"

userguide/install.rst, userguide/snippets/alertevents.rst, userguide/snippets/upgradingazfspool.rst, userguide/storage.rst, userguide/zfsprimer.rst
- Rework text about OpenZFS feature flags into a new subsection of the ZFS Primer.
- Add a link to zpool-features(7).
- Add references to this new section where needed throughout the guide.
=> 58392 (11.2-U3): Add ZFS Feature Flags section and new references to this section

userguide/tasks.rst
Reorganize and reedit the section for better flow and clarity.
Update "Init/Shutdown Command or Script Options" table to include clarified info about the "Script" and "When" fields.
=> 69625: Rework Init/Shutdown Tasks section.

userguide/intro.rst, userguide/services.rst
Also sync up "Port" field description with updated help text.
=> 75675: Add "Host" field to TFTP Configuration Options table:

userguide/intro.rst, userguide/services.rst
Sync up "Port" field description with updated help text.
Also adjust table to match angulargui. This should allow for easier cherry-picking in the future.
=> 60822: Add "Host" field to TFTP Configuration Options table:

userguide/Makefile, userguide/conf.py
Removed broken patch from conf.py and add replacement to Makefile.
No adjustment to PDF building is necessary
=> Fix broken arrow replacement for |menuselection|

userguide/system.rst
Cherry-pick previous commits to master and rework instructions to match legacy UI.
=> Work with Support to refine SED docs

userguide/intro.rst, userguide/tasks.rst
Add intro entry.
Cherry-pick from #886 with image update dropped and one extra change:
Unify SMART Test Options table structure so cherry-picks between branches will be smoother.
=> NAS-100611: Add "All Disks" field to SMART Test Options table:

userguide/system.rst
Rework the note box into the surrounding text and describe the conditions for using an encrypted volume for the system dataset.
cherry-pick from PR #804
=> NAS-101187: Update guidance about moving the system dataset to an encypted volume.

userguide/system.rst
Rework the note box into the surrounding text and describe the conditions for using an encrypted volume for the system dataset.
(cherry-pick #804)
=> NAS-101187: Update guidance about moving the system dataset to an encrypted volume.

userguide/system.rst
Text was already correct for CAs, one small change was needed for Certificate creation.
=> NAS-101123: Indicate which CA/Cert create fields are hidden by type.

userguide/intro.rst, userguide/services.rst
cherry-pick from #984 with 11.2U4 specific intro entry removed.
Duplicate field description from 11.2-legacy branch.
Add intro entry
=> NAS-101219: Add "Administrators Group" field to "Global SMB Configuration Options" table

userguide/install.rst
Add back vmware text mistakenly deleted in https://github.com/freenas/freenas-docs/commit/26039ceedeb4bc48362c10adc529f720230b97d1. This brings all branches back up into sync with this change.
=> NAS-101555: vmware text improvements master

userguide/system.rst
verify the removed alert is not mentioned in alertevents.rst
TrueNAS html build test: no issues.
=> NAS-100716: Remove TrueNAS note about system datasets.

userguide/directoryservice.rst
Relates to PR #1039 
The "unix extensions" field has not been removed yet. There is a related ticket for that, though.
=> NAS-101692 Remove 3 fields from Directory Services -> Active Directory

userguide/snippets/console_menu.rst
Remove text about disabling console menu as it is no longer visible in FreeNAS or TrueNAS 11.2U4.
Fix text from Pools back to Volumes for the legacy UI.
Confirm console-menu.png does not need to be updated.
=> NAS-101771: Review console_menu.rst and related image

userguide/sharing.rst
Fixes build warning for 11.2-legacy branch
Checked FreeNAS/TrueNAS 11.2U4.1 systems and confirmed with Andrew that text is relevant.
TrueNAS HTML build: no issues.
=> Port User Quota Administration section into sharing.rst to fix build warning

userguide/snippets/alertevents.rst, userguide/system.rst
- TrueNAS guide changes only
- Update alert message for disk mismatches
- Add text to Failover section about HA icon becoming unavailable for disk number mismatches
=> NAS-100087 , NAS-101289 : TrueNAS disk number mismatches

userguide/snippets/alertevents.rst, userguide/system.rst
Cherry-pick from #1086 
- TrueNAS guide changes only
- Update alert message for disk mismatches
- Add text to Failover section about HA icon becoming unavailable for disk number mismatches
=> NAS-100087 , NAS-101289 : TrueNAS disk mismatches

userguide/sharing.rst
- verified this field exists in new/legacy UI for 11.2
=> RM 9053: Add missing "Time Machine Quota" field to sharing.rst

userguide/conf.py, userguide/directoryservices.rst, userguide/network.rst, userguide/services.rst, userguide/snippets/alertevents.rst, userguide/snippets/console_menu.rst, userguide/storage.rst, userguide/system.rst, userguide/tn_initial.rst, userguide/tn_options.rst
Register new replacements in conf.py
Search through the guide and replace every relevant instance of "node", "storage controller", and variants of the terms.
Current replacement term setting: "storage controller" and variants
TrueNAS html build testing: no related warnings
FreeNAS html build testing: no issues
=> NAS-100122: Replace all textual uses of the terms "node" and "storage controller"

userguide/conf.py, userguide/directoryservice.rst, userguide/network.rst, userguide/services.rst, userguide/snippets/alertevents.rst, userguide/snippets/console_menu.rst, userguide/storage.rst, userguide/system.rst, userguide/tn_initial.rst, userguide/tn_options.rst
Register new replacements in conf.py
Search through the guide and replace every relevant instance of "node", "storage controller", and variants of the terms.
Current replacement term setting: "storage controller" and variants
TrueNAS html build testing: no related warnings
FreeNAS html build testing: no issues
cherry-pick #1135 and crunch on it a bit to get it working correctly for master branch
=> Nas100122 node term update master

userguide/directoryservices.rst
manual rework of #1113 
cherry-pick is not possible due to file rename.
freenas HTML build test: no issues.
=> 58083: Manually port relevant changes to 11.2-angular branch

userguide/services.rst
Wrapped entry in ifdef statements.
=> NAS-100987: Add Asigra entry to list at beginning of services.rst

userguide/directoryservices.rst
Update directoryservices.rst replacement to use |Ctrlr-term-1-2| in angulargui branch.
TrueNAS html build test: no issues.
=> NAS-101771: Fix replacement error between angulargui and master branches

userguide/intro.rst, userguide/system.rst
Add entry to U5 section in intro.
Add generalized text description of OAuth options and adjust Cloud Credential Options table to point to this description where appropriate.
=>  NAS-102147: Add text about OAuth with Cloud Providers.

userguide/intro.rst, userguide/system.rst
cherry-pick from 11.2-legacy PR #1197 and remove intro entry
Add generalized text description of OAuth options and adjust Cloud Credential Options table to point to this description where appropriate.
=> NAS-102147: Add text about OAuth with Cloud Providers.

userguide/intro.rst, userguide/tasks.rst
Note that the doc changes in the PR are purposely different from #1177 . This is because the slight difference in UI design.
=> NAS-102018 Add docs for cloud sync stop button

userguide/intro.rst, userguide/virtualmachines.rst
NOTE: I decided to comment out the docker section instead of deleting it. This is because docs still need to be written on how to get a docker vm running (since the docker vm type was removed from the UI) and I may be able to use information from the section.
=> NAS-101051 comment out all of docker docs

userguide/storage.rst
Added missing 'apply permissions to child datasets' checkbox
Go through Andrew's notes on ACLs, ACEs, and inheritance flags and update related descriptions as needed.
=> NAS-102047: Update ACL Manager section from Andrew's notes

userguide/intro.rst, userguide/system.rst
- Add intro entry for field changes
- Update 'Cloud Credential Options' table OAuth descriptions and port current help text link for hubiC description
- Update OAuth section text
=> NAS-102299: Update OAuth Cloud Credentials descriptions

userguide/sharing.rst
- No intro entry needed.
- Add text about what is or isn't removed when deleting an SMB share.
=> NAS-102087: Add clarification about SMB share delete

userguide/storage.rst, userguide/system.rst
- text is ready for review/refinement.
- All behaviors have been verified in 11.3 Beta1 except using the recovery key file to import an encrypted pool. That test is being held up by an unrelated bug.
=> NAS-102561: Finish draft rewrite of Pool Encryption docs

userguide/snippets/alertevents.rst
- Investigated directoryservices.rst and found text related to the alerts was already present.
- As previously discussed, no intro entry is necessary.
=> NAS-100007: Add entry for AD related alerts

userguide/storage.rst
- Add text to indicate encrypted disks cannot be onlined
- Clean up the duplicated text between the ifdefs
- small text cleanups
- FreeNAS and TrueNAS HTML build testing: no issues.
=> NAS-102777: Update 'replace failed disk' section

userguide/booting.rst, userguide/intro.rst, userguide/snippets/usingui.rst
- Rework two existing note boxes in booting.rst to make a list of UI usage suggestions
- Remove unnecessary FreeNAS ifdefs from the section.
- HTML build tests: no issues.
=> NAS-102301: Add general usage note about expanding list entries

userguide/intro.rst
- Add intro entry for removed option
- Review System/Cloud Credentials images and text: no further changes needed.
=> NAS-102946: Remove Amazon Cloud Drive credential option

userguide/network.rst, userguide/system.rst
Update example to show default subnet mask.
Confirm VIP descriptions are correct for subnet 32.
=>  NAS-102623: Small update to Network/Interfaces 'IP Address' description.

userguide/conf.py, userguide/intro.rst, userguide/system.rst
- Move duplicate text into a separate subsection in System/Update docs.
- Add new icon replacement in conf.py
- Expand text about what happens after an update is started.
- Add intro entry pointed to new subsection.
=> NAS-102879: Expand update in progress text

userguide/tasks.rst
- Include link to Backblaze documentation about lifecycle rules.
=> NAS-103369: Add text about B2 sync default behavior.

userguide/reporting.rst, userguide/system.rst
- Remove obsolete sentence in reporting.rst
- Reapply original field name and description for System/Reporting `Graphite Server` option.
- Requires syncing with webui repo.
=> NAS-103528: Clean up remaining mentions of Graphite.

userguide/intro.rst
The Storage Disks and Controllers section of the FreeNAS User Guide contains lots of information about obsolete disk controllers and implies using hardware RAID.  Remove it.
=> DOCS-69: Remove obsolete disk information

userguide/tasks.rst
- Add paragraph describing replication behavior when the destination dataset has snapshots that don't match the source snapshots.
=> NAS-103507: Update replication section intro:

userguide/system.rst
- Review the wider section and touch up a few spots.
- Add text to the System/Failover/Master field description for changing the primary Controller.
Resync this with the webui PR, when that is opened.
=> NAS-103141: Update TrueNAS Failover section

userguide/system.rst
- Rework recommendation for using sedhelper and sedutil-cli slightly.
- Add statement that a SED can be configured before or after adding the device to a pool.
=> NAS-103567: Update SED documentation

userguide/system.rst
- Failover message that displays during update process is now more generic. Update text to match.
=> NAS-104069: Update HA update process slightly

userguide/tasks.rst
- Update to show "Properties" is not an option for LEGACY engine replications.
=> NAS-104220: Update Advanced Replication Options table

userguide/storage.rst
- Add text about the directory/file browser identifying datasets that have an ACL.
- Add text about being required to use the ACL manager for dataset permissions.
- Remove obsolete warning about top-level datasets (these can no longer have their permissions changed in the web ui).
=> NAS-104321: Update ACL management text:

userguide/tasks.rst
In addition to the two failure modes already listed, a third failure mode occurs when files are stored in S3 Glacier or Glacier Deep Archive storage classes.
=> rclone sync delete failures w/ s3 glacier

userguide/system.rst
- Update this section to reflect the feature release and bugfix update behavior.
- Generalize the text about Production Use trains and add the 11.2 and 11.3 trains.
- TrueNAS HTMl build test: no issues.
=> DOCS-97: TrueNAS Updates and Trains rework

userguide/accounts.rst, userguide/conf.py
- Update conf.py to reversion FreeNAS guide for 11.3-RELEASE
Update User Account Configuration table:
- Rewrite "Enable Password Logins" field description to match middleware logic and clarify the description.
- Clarify the Lock User and Permit Sudo field descriptions a little
TODO: open a PR in freenas/webui repo to sync these proposed changes with the angular UI. EDIT: 
https://github.com/freenas/webui/pull/3474
https://github.com/freenas/webui/pull/3475
=> DOCS-100: Update "Enable Password Login" field description

userguide/tasks.rst
Clarify software versions for destination systems and when installing py-libzfs might be required.
=> DOCS-282: Reword SSH+Netcat text.

userguide/virtualmachines.rst
Expand text about supported OSes for VirtIO driver and include links to VirtIO documentation.
Add note about AHCI for pre-Vista Windows OSes.
=> DOCS-67: Expand VM disk device mode text a little:

userguide/tasks.rst
Fixed outdated information and added more details in Periodic Snapshot Tasks section.
* Changed default naming schema to current value.
* Removed sentence stating that snapshot lifetime is automatically appended to name (not true in version 11.3)
* Added subsection about how snapshots are automatically removed and a related warning for modifying or deleting periodic snapshot tasks.
This information is true to the best of my knowledge and has been tested on a fresh Virtualbox installation of FreeNAS 11.3-U3.1.
=> 11.3 angular - periodic snapshot task documentation changes

userguide/network.rst
=> DOCS-579 Update network revert docs.
